### ISSUE TITLE
isSupportCanvas判断代码错了

### ISSUE THREAD

**Issue by zWingz** [ZENGzoe/vue-scratch-card#1]
![image](https://user-images.githubusercontent.com/13031838/54477398-628d9c80-4842-11e9-8556-440229064928.png)

应该是
```javascript
if(!this.isSupport())
```
你放的是一个`methods`, 他要执行才有结果, 不然就一直为`true`

**Comment by ZENGzoe** [comment]
感谢提醒，已经改过来惹～～谢谢～～～
